This is to push a 'Announcement Input Box' page.
Xfers/Operation-Automation pull request #5
Opened 2022-10-02 10:15 UTC by AnitaTT

Set the Welcome page as "Home" page, on top of the Welcome page, created 2 pages:
1. "Say_hello" page
2. "Message_Index" page.

Functions in the Message_Index Page:
1. create a new announcement with 2 input boxes, one is "Message Title", and the other is " Message Content".
2. show details of an announcement.
3. edit details of an announcement with the 2 same input boxes and update them to the index.

2022-10-02 10:46 UTC, ChiuWeiYi reviewed
generally ok with two suggestions 

1) refactoring the controller, can refer to the D.R.Y principle.

2) the name of column could be better. Can refer to MySQL styling 

looking forward to seeing slack features soon!

2022-10-05 07:00 UTC, ChihHaoTW requested changes
Got one suggestion, others look good to me!!

2022-10-05 07:00 UTC, ChihHaoTW commented on slack-announcement-scheduler/db/migrate/20221002090614_create_messages.rb
> +      t.text :when_to_announce
Suggest using datetime to store time format
```suggestion
      t.datetime :when_to_announce
```

2022-10-05 07:01 UTC, ChihHaoTW commented on slack-announcement-scheduler/db/migrate/20221002090614_create_messages.rb
> +      t.text :when_to_announce
And agree with WY
This should be named like `announce_time`

2022-10-05 12:27 UTC, ChihHaoTW approved these changes

2022-10-05 12:29 UTC, ChiuWeiYi approved these changes

2022-10-05 12:30 UTC, merged